import { readFileSync, writeFileSync } from 'node:fs';

const catalog = JSON.parse(readFileSync(new URL('../public/locales/zh-CN.json', import.meta.url), 'utf8')) as Record<string, string>;
const lines = ['// Generated by npm run i18n:types. Edit the locale catalogs, then regenerate.', "import type { MessageValue } from './i18n.js';", '', 'export interface MessageParameters {'];
for (const [key, text] of Object.entries(catalog)) {
  const params = [...new Set([...text.matchAll(/\{\{(\w+)\}\}/g)].map(match => match[1]!))];
  lines.push(`  '${key}': ${params.length ? '{ ' + params.map(name => `${name}: MessageValue`).join('; ') + ' }' : 'Record<string, never>'};`);
}
lines.push('}', '', 'export type MessageKey = keyof MessageParameters;', '');
const output = new URL('../src/i18n-types.ts', import.meta.url);
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== lines.join('\n')) {
    throw new Error('Translation types are stale. Run npm run i18n:types.');
  }
} else {
  writeFileSync(output, lines.join('\n'));
}
